### PR TITLE
Try system uvw package if possible

### PR DESCRIPTION
**Pull request by pemensik**
Uvw library is bundled. Try to use system library if cmake can detect
it. Fall back to bundled headers if not found.

### CODE REVIEW

**Comment by pemensik** [comment]
CMake module is exported since uvw 0.11, but it does not correctly exports used version. Minimal version therefore cannot be specified in find_package.

**Comment by pemensik** [comment]
Oh, it is not so simple. Recent uvw changed header names and renamed uvw::TcpHandle to uvw::TCPHandle.

**Comment by weyrick** [comment]
thanks @pemensik - we could also update the bundled uvw to a newer version, rather than the typedef?

**Comment by pemensik** [comment]
Of course. Depends on what minimal libuv should be supported. I tried to update on the first attempt to 2.3.5, which renamed uvw/loop.hpp to uvw/loop.h. That requires libuv 1.34, which failed CI of PR. Because ubuntu container supplies only libuv 1.30. What should be minimal supported libuv version, @weyrick?

**Comment by weyrick** [comment]
It's a good question - whatever builds I guess. I would actually like to move flamethrower over to conan for dependencies and get it up to date with the way we are doing build and github CI in pktvisor - see https://github.com/ns1labs/pktvisor and https://github.com/ns1labs/pktvisor/blob/develop/conanfile.txt ... but having a hard time finding the time.

**Review by weyrick — APPROVED** [review]
cool thanks!

**Pull request merged**
