### PR TITLE
DNS over QUIC support (old reference)

### PR DESCRIPTION
**Pull request by weyrick**
Implement DoQ according to the draft spec: https://datatracker.ietf.org/doc/draft-huitema-quic-dnsoquic/

Using Fastly's QUIC library https://github.com/h2o/quicly

- [x] First pass at integration
- [x] Make QUIC support optional at build time
- [x] Fix Travis-CI
- [ ] Cleanup XXX markers
- [ ] Add example to docs, pointing out QUIC proxy
- [ ] Check for mem leaks

### CODE REVIEW

**Comment by VanStratum** [comment]
Hello @weyrick , I am intersted by the functionnality offered by this pull
request and was wondering wether you had plans to merge it in the near future?
I may be able to help if necesary.

**Comment by weyrick** [comment]
> Hello @weyrick , I am intersted by the functionnality offered by this pull
> request and was wondering wether you had plans to merge it in the near future?
> I may be able to help if necesary.

Hi @VanStratum - great! It's been on ice for awhile but I'd love to see it get attention again, especially as there has been more interest in DoQ recently. I can't dedicate much time to it directly atm, but I can definitely help you get it in working order if you are able to look at it. There is probably a bit of merge work waiting to get it back inline with master, first.

**Comment by VanStratum** [comment]
Okay. I started merging, and was wondering when the case statement was reached in the following code segment of trafgen.cpp l.328 in the master branch, since as far as I can tell the protocol field is never changed.
``` c++
    if (_traf_config->protocol == Protocol::UDP) {
        [...]
        _sender_timer->on<uvw::TimerEvent>([this](const uvw::TimerEvent &event, uvw::TimerHandle &h) {
			switch(_traf_config->protocol) {
				case Protocol::UDP: udp_send(); break;
				case Protocol::TCP:
         [...]
			}
        });
    }
```

**Comment by weyrick** [comment]
> Okay. I started merging, and was wondering when the case statement was reached in the following code segment of trafgen.cpp l.328 in the master branch, since as far as I can tell the protocol field is never changed.

@VanStratum I agree, it seems to me that `protocol` in that lambda should always be UDP. Probably some code that got shifted around that now needs to be cleaned up.

**Comment by VanStratum** [comment]
> Probably some code that got shifted around that now needs to be cleaned up.
Indeed, it was dead code that was deleted in the PR.

**Comment by VanStratum** [comment]
@weyrick I finished the merge and will soon start testing. Do you want me to start another pull request with the merge, or use another way?

**Comment by weyrick** [comment]
> @weyrick I finished the merge and will soon start testing. Do you want me to start another pull request with the merge, or use another way?

@VanStratum yes let's start a separate pull request, and iterate there. I'm also expecting that the quic library interface has changed over time, and I recall not fully completing the proper memory management so we will have to review that as well.

**Comment by weyrick** [comment]
Hi @VanStratum how is this coming? There is an IETF hackathon coming up in a few weeks, and I may get some time to work on this (among other things).

**Comment by VanStratum** [comment]
I am still working on it, updating the calls to quicly has proved to be
quite tedious. I have nearly finished though.

**Comment by weyrick** [comment]
see https://github.com/VanStratum/flamethrower/tree/dns-over-quic

**Pull request closed without merging**
