### PR TITLE
DNS over HTTPS support

### PR DESCRIPTION
**Pull request by jwijenbergh**
This PR adds the ability to flame over DoH as described in RFC8484. I have wrote and used this implementation for my bachelor's thesis at the Radboud University. The DoH implementation works currently.
That being said, there is still a list of things that can be improved. For example, right now, the DoH class has a lot of the same code as DoT. It would be nice to abstract this duplicate code.
The HTTP/2 code is provided by the [NGHTTP2](https://nghttp2.org/) library. Some code was taken from the NGHTTP2 documentation.

example usage:

```flame -Q 100 -P https -M GET dns.example.net```

Below, there is a small list of what I have done and what is there to come in the next few weeks.
- [x] URL parsing
- [x] Add base64url parsing 
- [x] Add -M option for HTTPS GET and HTTPS POST
- [x] Create HTTPSSession class and implement it in trafgen and main
- [x] Code cleanup (e.g. simplifying, removing duplicate code & unnecessary bookkeeping)
- [x] Fix more than 100 outgoing queries per TCP connection
- [x] Do not hard code HTTP path ```/dns-query``` (some servers use something else)
- [x] Document DoH support
- [x] Update Docker + CI file with the nghttp2 dependency
- [x] Make DoH support optional, similar to #11

### CODE REVIEW

**Comment by weyrick** [comment]
Thanks @jwijenbergh! We appreciate the contribution. We'll get you some feedback on this soon.

**Comment by jwijenbergh** [comment]
> Thanks @jwijenbergh! We appreciate the contribution. We'll get you some feedback on this soon.

No problem! Feedback would be helpful, thanks. In the meantime I will work on the checklist.

**Comment by weyrick** [comment]
> Hello! I just noticed this PR (despite having worked on the same thing on my side). I'd like to know if you had any update on your plans / feedback about this ?

@chbruyand would you like to create a separate PR to compare the implementations?

**Comment by chbruyand** [comment]
> > Hello! I just noticed this PR (despite having worked on the same thing on my side). I'd like to know if you had any update on your plans / feedback about this ?
> 
> @chbruyand would you like to create a separate PR to compare the implementations?

I stopped working on it when I saw this PR and don't see the point of finishing it if you plan to merge that ? Would be better to add stuffs based on that if you are fine with the job done here.

**Comment by jwijenbergh** [comment]
First of all, sorry for the late reply. I was quite busy these last few days.

> @jwijenbergh this is looking really good. I have one general comment: I'd like to rename `https` to `doh` in the Protocol, docs, command line options, etc. I think this is now a common enough term,

This is a good point. I called it https to be more in line with the dot naming scheme. I will rename the files and classes to doh.

> secondly I want to leave open the possibility of using flamethrower for general HTTPS testing without it being specific to DNS. This has been requested at various times, and seems like a small lift once this PR lands - so also please keep that in mind in `httpsession` code: that we may offer a mode where the payload and headers are not specifically DNS.

I can separate the nghttp2 code from the DoH class. However, do note that nghttp2 can only be used for http/2 and not for e.g. http/1.1. 

> I'd also like to rename `tcptls` to `dot` but we can address that in a separate PR.
> Let us know how else we can help get this landed. It would be great to start building out a real test suite here, but once it nears completion we can at least do some manual testing.

I will work on these few issues and do some refactoring in the next week. Stay tuned

**Comment by weyrick** [comment]
> I will work on these few issues and do some refactoring in the next week. Stay tuned

Sounds great. Also, see PR #30 which we'll land soon.

**Comment by MichaelKearnsSoftwire** [comment]
Hi @jwijenbergh -- I have been playing around with this branch against some DNS servers and it has been very useful, so thanks very much for your work here :)

One of the servers currently only supports HTTP/1.1 and not HTTP/2. Am I right in thinking that this PR doesn't currently support HTTP/1.1 due to its usage of nghttp2? If so, do you have any pointers on how I could go about adding HTTP/1.1 support?

Looking at the [RFC](https://tools.ietf.org/html/rfc8484#section-5.2) I can see that HTTPS/1.1 is discouraged but not forbidden.

**Comment by jwijenbergh** [comment]
@weyrick
> 
> > I will work on these few issues and do some refactoring in the next week. Stay tuned
> 
> Sounds great. Also, see PR #30 which we'll land soon.

I did see this PR, now that it is merged I will rebase my branch and continue working on your comments. Thanks :)

@MichaelKearnsSoftwire
> Hi @jwijenbergh -- I have been playing around with this branch against some DNS servers and it has been very useful, so thanks very much for your work here :)
I'm glad it's useful, let me know once problems arise.

> One of the servers currently only supports HTTP/1.1 and not HTTP/2. Am I right in thinking that this PR doesn't currently support HTTP/1.1 due to its usage of nghttp2? If so, do you have any pointers on how I could go about adding HTTP/1.1 support?
> Looking at the [RFC](https://tools.ietf.org/html/rfc8484#section-5.2) I can see that HTTPS/1.1 is discouraged but not forbidden.

I did not implement HTTP/1.1 for DoH because I did not notice any DoH server using it instead of HTTP/2 (and the fact that the RFC recommends HTTP/2). Can you share which server this is? I want to abstract the HTTP code and potentially allow support for HTTP/1.1. This does require a new library, because nghttp2 doesn't support HTTP/1.1. Thanks for your comment.

**Comment by weyrick** [comment]
@jwijenbergh Just checking in, anything we can help with to get this landed?

**Comment by jwijenbergh** [comment]
> @jwijenbergh Just checking in, anything we can help with to get this landed?

I am still working on this when I have the time. I am not sure at the moment how I want to separate the different classes. I want to have a class that just does TLS so that I can build my DoH code on top of it (to prevent duplicate code). Right now the class TCPTLS can not really be used for this due to the fact that it directly builds on top of the TCP class, which prevents further processing of the data. I also want to seperate my DoH code such that the HTTP/2 code is in a separate class which can later be re-used for standard HTTP testing.

So what I want is the following:

- TLS class that only sets up TLS
- HTTP/2 class that does http/2.
- DoH class that builds on top of the HTTP/2, TLS and TCP class
- DoT class that uses the TLS class + TCP class

Would something like this be okay with you? This does mean that I have to change the start_tcp_session function in the trafgen class (because not all the classes directly builds on top of TCPSession).

What do you think is the best way of implementing something like this? I am definitely still working on this.

**Comment by weyrick** [comment]
@jwijenbergh Thanks for the update. 

I've reviewed your branch again and what I'd really like to do is break your TODO list into two phases. 

Let's work through a bit of code cleanup, making DoH optional at build time, and look at the 100 outgoing connection limit you mention -- but otherwise land your PR without doing the class refactor. This will get DoH support in much sooner and will benefit more people. 

Once it's landed, we can revisit the class refactor as a separate PR (and I think your thoughts above do make sense at a high level).

How does that sound?

**Comment by jwijenbergh** [comment]
> @jwijenbergh Thanks for the update.
> 
> I've reviewed your branch again and what I'd really like to do is break your TODO list into two phases.
> 
> Let's work through a bit of code cleanup, making DoH optional at build time, and look at the 100 outgoing connection limit you mention -- but otherwise land your PR without doing the class refactor. This will get DoH support in much sooner and will benefit more people.
> 
> Once it's landed, we can revisit the class refactor as a separate PR (and I think your thoughts above do make sense at a high level).
> 
> How does that sound?

This sounds like a good idea! I will start to have another look on the 100 query limit. Making DoH support optional shouldn't be too hard to implement. I will let you know if I get stuck somewhere.

**Comment by jwijenbergh** [comment]
The 100 query limit for each tcp connection is due to the fact that most servers only allow 100 concurrent streams. You can test this with: ```nghttp --max-concurrent-streams=200 -nv url``` to see that most servers will return a 100 concurrent streams limit, even though you want 200 concurrent streams:
```
recv SETTINGS frame <length=12, flags=0x00, stream_id=0>
(niv=2)
[SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
```

 Due to this, nghttp2 sets this 100 limit by default. When multiple tcp connections are used ('concurrent traffic generators') more than 100 outgoing queries is easily obtained:

```
flame -c 2 -Q 200 -P doh url
```

I will leave this as a limitation in the implementation as of now. If someone knows thow to properly handle this, then that would be great

**Comment by weyrick** [comment]
@jwijenbergh Sorry, I missed that you asked a question here. But I am afraid I don't understand the question?

**Comment by jwijenbergh** [comment]
I finally had some time to work on this again.

See 71de378 for the 100 stream limit fix. Aside from maybe some documentation, this implementation is done. Please let me know if there is anything that I can still improve. It would be great if this can be merged soon.

**Comment by weyrick** [comment]
@jwijenbergh Thanks again for your work on this, we're going to work on landing this as soon as possible.

**Comment by tomaskrizek** [comment]
> When this is received, data can be sent such that a stream limit higher than 100 (in DoH the stream limit is given by the `-q` command line option) can be achieved if servers advertise them in the settings frame.

What happens when the SETTINGS frame received from the server doesn't contain the `SETTINGS_MAX_CONCURRENT_STREAMS` value? According to [RFC 7540, section 6.5.2](https://tools.ietf.org/html/rfc7540#section-6.5.2) it means the server imposes no limit. If the nghttp2's default of 100 concurrent streams is kept in this case, it can skew the results.

Knot Resolver's http module (in v5.1.2) doesn't include `SETTINGS_MAX_CONCURRENT_STREAMS` in the SETTINGS frame. I'm not saying it's ideal, just that it happens.

I think it's best to allow user to customize the concurrent streams (default) value, which can then be overridden by the server's SETTINGS frame. I'm not very familiar with flamethrower or this implementation, so I'm not sure how difficult it would be to support this behavior.

**Comment by jwijenbergh** [comment]
> > When this is received, data can be sent such that a stream limit higher than 100 (in DoH the stream limit is given by the `-q` command line option) can be achieved if servers advertise them in the settings frame.
> 
> What happens when the SETTINGS frame received from the server doesn't contain the `SETTINGS_MAX_CONCURRENT_STREAMS` value? According to [RFC 7540, section 6.5.2](https://tools.ietf.org/html/rfc7540#section-6.5.2) it means the server imposes no limit. If the nghttp2's default of 100 concurrent streams is kept in this case, it can skew the results.
> 
> Knot Resolver's http module (in v5.1.2) doesn't include `SETTINGS_MAX_CONCURRENT_STREAMS` in the SETTINGS frame. I'm not saying it's ideal, just that it happens.
> 
> I think it's best to allow user to customize the concurrent streams (default) value, which can then be overridden by the server's SETTINGS frame. I'm not very familiar with flamethrower or this implementation, so I'm not sure how difficult it would be to support this behavior.

Thanks for your insight.

Indeed, if the settings frame does not consist of the `SETTINGS_MAX_CONCURRENT_STREAMS` value, the default of 100 is kept which can result in timeouts if the batch count is higher than 100. In a way the default of 100 does make sense as this is the minimum of max concurrent streams servers should handle. This means that we are guaranteed to never overload a DoH server with streams.

Indeed, the RFC states that initially it imposes no limit.

The problem in our case is that the settings frame is received *after* sending the requests. This means that we do not properly agree on a max concurrent streams limit. So even if servers advertise a max concurrent stream setting of higher than 100, this is never agreed before sending the batch. There are two ways I considered fixing this:
1. Wait explicitly for the settings frame to arrive. This means the 100 limit is kept if servers don't advertise the `SETTINGS_MAX_CONCURRENT_STREAMS` setting. It can also cause problems if no settings frame is sent from the server (as you correctly stated). The advantage of this is that we are always guaranteed to not overload the server.
2.  Another option would be to set the following property in the initialization of nghttp2: https://nghttp2.org/documentation/nghttp2_option_set_peer_max_concurrent_streams.html?highlight=set_peer#c.nghttp2_option_set_peer_max_concurrent_streams. With this option it's possible to set an arbitrarily number of initially max concurrent streams. 

I did not opt for the second solution as it felt like a better idea to agree upon a limit before sending, even though the RFC does not state this. Thinking about it some more, and looking at other implementations. I think that the second fix is indeed better than the first as it causes less problems. To see an interesting discussion about this topic in a different implementation, see: https://github.com/envoyproxy/envoy/pull/3658

Thoughts?

**Comment by jwijenbergh** [comment]
> > When this is received, data can be sent such that a stream limit higher than 100 (in DoH the stream limit is given by the `-q` command line option) can be achieved if servers advertise them in the settings frame.
> 
> What happens when the SETTINGS frame received from the server doesn't contain the `SETTINGS_MAX_CONCURRENT_STREAMS` value? According to [RFC 7540, section 6.5.2](https://tools.ietf.org/html/rfc7540#section-6.5.2) it means the server imposes no limit. If the nghttp2's default of 100 concurrent streams is kept in this case, it can skew the results.
> 
> Knot Resolver's http module (in v5.1.2) doesn't include `SETTINGS_MAX_CONCURRENT_STREAMS` in the SETTINGS frame. I'm not saying it's ideal, just that it happens.
> 
> I think it's best to allow user to customize the concurrent streams (default) value, which can then be overridden by the server's SETTINGS frame. I'm not very familiar with flamethrower or this implementation, so I'm not sure how difficult it would be to support this behavior.

In this case, NGHTTP2 sets it to 'unlimited', see [this](https://github.com/nghttp2/nghttp2/blob/c3b46625633cd9a4519f6fbcd9048127b84a5514/lib/nghttp2_session.h#L103) and [this](https://github.com/nghttp2/nghttp2/blob/7b46edb483a47a2a0d558034be8c44a49da35295/lib/nghttp2_session.c#L4438)

I tested my flamethrower branch on a local knot resolver and got more than 100 streams.

So it works like this:
- Initially the default max streams is set to 100
- If the settings frame is received, it sets the value to the new concurrent streams OR to 'unlimited' (`0xffffffff`) if none is provided

Because we explicitly wait for the setting frame to arrive, and the settings frame *MUST* be sent, even if empty (https://tools.ietf.org/html/rfc7540#section-3.5), this should work well in practice.
Some implementations do not wait for the settings frame to be received and simply set the default of 100 to some value with the function [`nghttp2_option_set_peer_max_concurrent_streams`](https://nghttp2.org/documentation/nghttp2_option_set_peer_max_concurrent_streams.html). For example, see https://github.com/envoyproxy/envoy/pull/3658.
We can also do this instead of waiting for the settings frame, however, this can mean that we are overloading servers that actually only want an x amount of streams at maximum. However, as you mentioned, this is legal as the default in the RFC is unlimited and not 100. Thoughts?

**Comment by tomaskrizek** [comment]
> * Initially the default max streams is set to 100 ([for completeness, this is done when creating a session](https://github.com/nghttp2/nghttp2/blob/7b46edb483a47a2a0d558034be8c44a49da35295/lib/nghttp2_session.c#L457))
> 
> * If the settings frame is received, it sets the value to the new concurrent streams OR to 'unlimited' (`0xffffffff`) if none is provided

I see, thanks for the detailed explanation!

> Some HTTP/2 implementations do not wait for the settings frame to be received and simply set the default of 100 to some value with the function [`nghttp2_option_set_peer_max_concurrent_streams`](https://nghttp2.org/documentation/nghttp2_option_set_peer_max_concurrent_streams.html). For example, see [envoyproxy/envoy#3658](https://github.com/envoyproxy/envoy/pull/3658).
> We can also do this instead of waiting for the settings frame, however, this can mean that we are overloading servers that actually only want an x amount of streams at maximum. However, as you mentioned, this is legal as the default in the RFC is unlimited and not 100. This can also be considered as a solution, as I do not know if waiting for the settings frame is actually good practice.

I think using the nghttp2's default limit of 100 (until SETTINGS frame is received) makes sense, since the it'd be rare to see a lower server-side limit in practice. Then, the first received SETTINGS frame updates the concurrent streams limit to the actual value the server imposes, so that should work fine. 

Waiting for the SETTINGS frame doesn't simulate what real clients actually do and it imposes an extra RTT/2 latency. On the other hand, the issue with allowing more than 100 (which seems to be a "safe" limit) right from the start is that the server will probably reset those extra streams.

I think going with 100 concurrent stream limit until SETTINGS frame is received most closely resembles the behavior of most DoH clients. Since it should be rare to see such high-qps clients to open that many streams until SETTINGS frame is received, I think it could be a valid choice to establish a new connection in these cases (or perhaps just holding off on the queries or throwing them away could be also acceptable for some use-cases). 

An implementation note: not sure if it's relevant here, but beware that exceeding the configured peer_max_concurrent_streams changes the behavior of `nghttp2_session_send()` - [related docs](https://github.com/nghttp2/nghttp2/pull/1489).

**Comment by jwijenbergh** [comment]
Thanks for your reply.

> I think going with 100 concurrent stream limit until SETTINGS frame is received most closely resembles the behavior of most DoH clients. Since it should be rare to see such high-qps clients to open that many streams until SETTINGS frame is received, I think it could be a valid choice to establish a new connection in these cases (or perhaps just holding off on the queries or throwing them away could be also acceptable for some use-cases).

Agreed, however this does not work for flamethrower as it is now. If I do not wait for the settings frame, then every batch is limited to 100 streams. To explain why this is, we will look at an example:

If we want to send 150 queries for each TCP connection we do the following with flamethrower
`flame -P doh -q 150 (150 streams/batch count) -Q 150 (max 150 as rate limit) -c 1 (1 tcp connection per flame process) example.com/dns-query`
In this case, every iteration of the flamethrower process will do the following:
- Setup one fresh tcp connection
- Send 150 queries through 150 streams

For every iteration, the settings frame is received too late and NGHTTP2 only sends 100 queries, instead of 150 (testing on a server where `SETTINGS_MAX_CONCURRENT_STREAMS` is set to 200). Do you know of a better way to handle this? It would be nice to re-use the NGHTTP2 session but this is not easy to implement as it stands currently.
> An implementation note: not sure if it's relevant here, but beware that exceeding the configured peer_max_concurrent_streams changes the behavior of `nghttp2_session_send()` - [related docs](https://github.com/nghttp2/nghttp2/pull/1489).

I did see this pr a few days ago, thanks. This is already how I suspected `nghttp2_session_send` works.

**Comment by tomaskrizek** [comment]
> For every iteration, the settings frame is received too late and NGHTTP2 only sends 100 queries, instead of 150 (testing on a server where `SETTINGS_MAX_CONCURRENT_STREAMS` is set to 200). Do you know of a better way to handle this?

Are the queries sent in a single batch, all at once? I wonder if waiting for the SETTINGS frame limit is useful:

- If the server does support more than N concurrent streams, it makes no difference.
- If the server supports less than N concurrent streams, does knowing this number make a difference? If N queries have to be sent in a single batch and server allows only N concurrent streams, is this handled any differently?

Perhaps it might be best to set `nghttp2_option_set_peer_max_concurrent_streams()` to unlimited and let the user select proper values through the `-q/-Q/-c` arguments - although it might need to be properly documented.

**Comment by jwijenbergh** [comment]
> Are the queries sent in a single batch, all at once? I wonder if waiting for the SETTINGS frame limit is useful:

They are sent like this: https://github.com/jwijenbergh/flamethrower/blob/master/flame/trafgen.cpp#L134
So they get queued by `nghttp2_session_send` one after another, and as I said this does not work properly as the settings frame is not received yet.

> If the server does support more than N concurrent streams, it makes no difference.

This does make a difference here, right now sending more than 100 concurrent streams works. For example, we can send 200 concurrent streams if the server advertises ```SETTINGS_MAX_CONCURRENT_STREAMS: 200```. This does not work if we do not wait for the settings frame. See 71de378

> If the server supports less than N concurrent streams, does knowing this number make a difference? If N queries have to be sent in a single batch and server allows only N concurrent streams, is this handled any differently?

For this case it does indeed not make a difference.

> Perhaps it might be best to set `nghttp2_option_set_peer_max_concurrent_streams()` to unlimited and let the user select proper values through the `-q/-Q/-c` arguments - although it might need to be properly documented.

Even better, do not set it to unlimited but set it equal to `-q` argument?

Still, I think the way I have done it now is not the worst idea (waiting for the settings frame), as this always ensures we do not go over a server's limit. 

I appreciate your input.

**Comment by weyrick** [comment]
Travis got confused here somehow - I confirmed it is green here https://travis-ci.com/github/DNS-OARC/flamethrower/builds/164396366

**Comment by jwijenbergh** [comment]
> Travis got confused here somehow - I confirmed it is green here https://travis-ci.com/github/DNS-OARC/flamethrower/builds/164396366

Thanks, I noticed that travis was giving a weird error.

**Comment by weyrick** [comment]
Thanks again for this great contribution!

**Comment by jwijenbergh** [comment]
> Thanks again for this great contribution!

No problem! If @tomaskrizek still has some additional comments, I will create a separate PR for this. 

Thanks for the merge.

**Comment by tomaskrizek** [comment]
> > If the server does support more than N concurrent streams, it makes no difference.
> 
> This does make a difference here, right now sending more than 100 concurrent streams works. For example, we can send 200 concurrent streams if the server advertises `SETTINGS_MAX_CONCURRENT_STREAMS: 200`. This does not work if we do not wait for the settings frame (it will then only send 100 requests). See [71de378](https://github.com/DNS-OARC/flamethrower/commit/71de3786704901c936a3127e591e2cb34eeb196d)

I wasn't clear here. I was considering a scenario where `nghttp2_option_set_peer_max_concurrent_streams()` is initially set to unlimited (using the RFC default instead of nghttp2).

> > If the server supports less than N concurrent streams, does knowing this number make a difference? If N queries have to be sent in a single batch and server allows only N concurrent streams, is this handled any differently?
> 
> For this case it does indeed not make a difference.

> Even better, do not set it to unlimited but set it equal to `-q` argument?

That might be good as well, although I'm not sure if timeouts or outstanding queries wouldn't be an issue.

If it was set to `-q`, perhaps there could also be an additional check: anytime a SETTINGS frame with SETTINGS_MAX_CONCURRENT_STREAMS is received, verify its value is lower of equal to the user-set limit.

**Comment by jwijenbergh** [comment]
> I wasn't clear here. I was considering a scenario where `nghttp2_option_set_peer_max_concurrent_streams()` is initially set to unlimited (using the RFC default instead of nghttp2).
Ah, thanks for the explanation. Indeed, this makes no difference then. The way it is now should work fine (waiting for the settings frame). If people report issues with this approach, I will consider `nghttp2_option_set_peer_max_concurrent_streams`.

> 
> That might be good as well, although I'm not sure if timeouts or outstanding queries wouldn't be an issue.
> 
> If it was set to `-q`, perhaps there could also be an additional check: anytime a SETTINGS frame with SETTINGS_MAX_CONCURRENT_STREAMS is received, verify its value is lower of equal to the user-set limit.
Yes, see #49, In the ideal case we want to report to the user if SETTINGS_MAX_CONCURRENT_STREAMS is too low.

Thanks for your help, if you still have some additional feedback it might be better to:
- Make a pr in my branch
- Or contact me @ jeroenwijenbergh@protonmail.com

Thanks for your help!

**Pull request merged**
