### PR TITLE
Docker for flame

### PR DESCRIPTION
**Pull request by supernomad**
Implements a Docker based build for flamethrower. This could use some more tweaks for the overall size of the resulting image, but currently working as expected.

### CODE REVIEW

**Comment by supernomad** [comment]
:disappointed: kicked off the push build again got this: 
```shell
$ rvm $brew_ruby do brew update 1>/dev/null
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.7.mavericks.bottle.tar.gz
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by fcelda** [comment]
I've a similar change I didn't commit. I think my version results in a smaller image but doesn't build ldns/libuv from source so it's probably more likely to break. What do you think, @supernomad?

```dockerfile
FROM ubuntu:disco AS build
ENV BUILD_DEPS g++ cmake make libldns-dev libuv1-dev pkgconf
RUN \
    apt-get update && \
    apt-get install --yes --no-install-recommends ${BUILD_DEPS}
COPY . /src
RUN \
    mkdir /tmp/build && \
    cd /tmp/build && \
    cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo /src && \
    make all tests && \
    ./tests

FROM ubuntu:disco AS runtime
ENV RUNTIME_DEPS libldns2 libuv1
RUN \
    apt-get update && \
    apt-get install --yes --no-install-recommends ${RUNTIME_DEPS} && \
    rm -rf /var/lib/apt/lists/*
COPY --from=build /tmp/build/flame /usr/local/bin/flame
ENTRYPOINT /usr/local/bin/flame
```

**Comment by supernomad** [comment]
@fcelda yea this definitely will result in a much smaller image I think the idea that apt will fail is likely a non issue. I just used the build scripts to keep in line with the travis build, not really because I thought it would fail via apt (also apt for bionic doesn't have the right libuv version)

More than happy to run with your version sir :+1:

**Comment by fcelda** [comment]
LGTM. Thanks!

**Pull request merged**
